import Foundation

/// One way to make or replace an ingredient that is not in the kitchen.
///
/// `options` is a list of groups; one item from every group is needed. So
/// buttermilk is `[["milk"], ["lemon juice", "white vinegar"]]`: milk, and
/// either acid.
struct Substitution: Hashable {
    let target: String
    let options: [[String]]
    let note: String
    /// A homemade version of the thing rather than a swap for it.
    let isHomemade: Bool

    init(_ target: String, _ options: [[String]], _ note: String, homemade: Bool = false) {
        self.target = target
        self.options = options
        self.note = note
        self.isHomemade = homemade
    }

    /// The ingredients this substitution actually uses, given the pantry.
    func uses(in index: PantryIndex) -> [String] {
        options.compactMap { group in group.first { index.has($0) } }
    }
}

enum Substitutions {
    static let all: [Substitution] = [
        // Dairy
        Substitution("buttermilk", [["milk"], ["lemon juice", "white vinegar", "apple cider vinegar"]], "1 cup milk + 1 tbsp lemon juice or vinegar, rested 5 minutes", homemade: true),
        Substitution("buttermilk", [["yogurt"], ["milk"]], "¾ cup yogurt thinned with ¼ cup milk", homemade: true),
        Substitution("buttermilk", [["sour cream"], ["milk"]], "¾ cup sour cream thinned with ¼ cup milk", homemade: true),
        Substitution("sour cream", [["yogurt"]], "plain yogurt, same amount"),
        Substitution("yogurt", [["sour cream"]], "sour cream, same amount"),
        Substitution("heavy cream", [["milk"], ["butter"]], "¾ cup milk + ¼ cup melted butter per cup (not for whipping)", homemade: true),
        Substitution("heavy cream", [["half and half"]], "half and half, same amount (thinner, will not whip)"),
        Substitution("half and half", [["milk"], ["heavy cream"]], "equal parts milk and cream", homemade: true),
        Substitution("half and half", [["milk"]], "whole milk, same amount"),
        Substitution("milk", [["evaporated milk"], ["water"]], "equal parts evaporated milk and water", homemade: true),
        Substitution("milk", [["almond milk"]], "plant milk, same amount"),
        Substitution("milk", [["half and half"], ["water"]], "half and half thinned with a little water", homemade: true),
        Substitution("cream cheese", [["mascarpone"]], "mascarpone, same amount"),
        Substitution("mascarpone", [["cream cheese"], ["heavy cream"]], "cream cheese beaten with a splash of cream", homemade: true),
        Substitution("ricotta", [["cottage cheese"]], "cottage cheese, drained and blended smooth"),
        Substitution("cottage cheese", [["ricotta"]], "ricotta, same amount"),
        Substitution("parmesan", [["swiss cheese"]], "gruyère or another hard, nutty cheese"),
        Substitution("mozzarella", [["monterey jack"]], "jack cheese, same amount"),
        Substitution("cheddar cheese", [["monterey jack"]], "jack or colby, same amount"),
        Substitution("butter", [["coconut oil"]], "coconut oil, same amount"),
        Substitution("butter", [["vegetable oil"]], "¾ the amount of oil (for cooking, not pastry)"),
        Substitution("butter", [["shortening"]], "shortening, same amount"),
        Substitution("shortening", [["butter"]], "butter, same amount"),
        Substitution("sweetened condensed milk", [["evaporated milk"], ["granulated sugar"]], "1 cup evaporated milk simmered with 1¼ cups sugar until thick", homemade: true),
        Substitution("evaporated milk", [["heavy cream"]], "cream, same amount"),
        Substitution("evaporated milk", [["milk"]], "milk simmered until reduced by half", homemade: true),
        Substitution("whipped topping", [["heavy cream"], ["powdered sugar"]], "cream whipped with a spoonful of powdered sugar", homemade: true),
        Substitution("eggs", [["applesauce"]], "¼ cup applesauce per egg, in baking only"),
        Substitution("eggs", [["flaxseed"], ["water"]], "1 tbsp ground flax + 3 tbsp water per egg, in baking", homemade: true),
        Substitution("eggs", [["bananas"]], "½ mashed banana per egg, in baking"),

        // Baking
        Substitution("brown sugar", [["granulated sugar"], ["molasses"]], "1 cup sugar + 1 tbsp molasses", homemade: true),
        Substitution("brown sugar", [["granulated sugar"], ["maple syrup"]], "1 cup sugar + 1 tbsp maple syrup", homemade: true),
        Substitution("brown sugar", [["granulated sugar"]], "white sugar, same amount (less chewy, less deep)"),
        Substitution("granulated sugar", [["brown sugar"]], "brown sugar, same amount, packed"),
        Substitution("granulated sugar", [["honey"]], "¾ cup honey per cup of sugar; reduce other liquid a little"),
        Substitution("powdered sugar", [["granulated sugar"], ["cornstarch"]], "1 cup sugar + 1 tbsp cornstarch, blended fine", homemade: true),
        Substitution("self-rising flour", [["all-purpose flour"], ["baking powder"], ["salt"]], "1 cup flour + 1½ tsp baking powder + ¼ tsp salt", homemade: true),
        Substitution("cake flour", [["all-purpose flour"], ["cornstarch"]], "1 cup flour minus 2 tbsp, plus 2 tbsp cornstarch", homemade: true),
        Substitution("cake flour", [["all-purpose flour"]], "all-purpose flour, same amount (slightly less tender)"),
        Substitution("bread flour", [["all-purpose flour"]], "all-purpose flour, same amount"),
        Substitution("whole wheat flour", [["all-purpose flour"]], "all-purpose flour, same amount"),
        Substitution("almond flour", [["almonds"]], "almonds ground fine in a food processor", homemade: true),
        Substitution("baking powder", [["baking soda"], ["cream of tartar"]], "¼ tsp baking soda + ½ tsp cream of tartar per tsp", homemade: true),
        Substitution("baking powder", [["baking soda"], ["buttermilk"]], "¼ tsp soda per tsp, and swap ½ cup of the liquid for buttermilk", homemade: true),
        Substitution("cornstarch", [["all-purpose flour"]], "twice the amount of flour"),
        Substitution("cornstarch", [["arrowroot"]], "arrowroot, same amount"),
        Substitution("vanilla extract", [["vanilla bean"]], "the seeds of half a bean per teaspoon"),
        Substitution("vanilla extract", [["maple syrup"]], "maple syrup, same amount"),
        Substitution("vanilla extract", [["bourbon"]], "bourbon, same amount"),
        Substitution("chocolate", [["cocoa powder"], ["butter"]], "3 tbsp cocoa + 1 tbsp butter per ounce of unsweetened chocolate", homemade: true),
        Substitution("chocolate chips", [["chocolate"]], "a bar, chopped"),
        Substitution("cocoa powder", [["chocolate"]], "1 oz unsweetened chocolate per 3 tbsp cocoa; cut 1 tbsp fat"),
        Substitution("honey", [["maple syrup"]], "maple syrup, same amount"),
        Substitution("honey", [["granulated sugar"], ["water"]], "1¼ cups sugar dissolved in ¼ cup water per cup", homemade: true),
        Substitution("maple syrup", [["honey"]], "honey, same amount"),
        Substitution("molasses", [["honey"]], "honey, same amount (lighter flavour)"),
        Substitution("molasses", [["brown sugar"]], "dark brown sugar dissolved in a little water"),
        Substitution("corn syrup", [["honey"]], "honey, same amount"),
        Substitution("corn syrup", [["granulated sugar"], ["water"]], "1¼ cups sugar dissolved in ¼ cup water per cup", homemade: true),
        Substitution("graham crackers", [["crackers"]], "any plain sweet cracker or cookie, crushed"),
        Substitution("bread crumbs", [["bread"]], "stale bread, toasted and blitzed", homemade: true),
        Substitution("bread crumbs", [["crackers"]], "crushed crackers, same amount"),
        Substitution("bread crumbs", [["rolled oats"]], "oats pulsed fine, same amount"),
        Substitution("pumpkin pie spice", [["cinnamon"], ["nutmeg"], ["ginger powder"]], "1 tsp cinnamon + ¼ tsp nutmeg + ¼ tsp ginger per teaspoon", homemade: true),
        Substitution("pumpkin pie spice", [["cinnamon"], ["nutmeg"]], "mostly cinnamon with a pinch of nutmeg", homemade: true),
        Substitution("pecans", [["walnuts"]], "walnuts, same amount"),
        Substitution("walnuts", [["pecans"]], "pecans, same amount"),
        Substitution("pine nuts", [["almonds"]], "slivered almonds, toasted"),
        Substitution("pine nuts", [["walnuts"]], "walnuts, chopped"),
        Substitution("raisins", [["dried cranberries"]], "dried cranberries, same amount"),
        Substitution("dried cranberries", [["raisins"]], "raisins, same amount"),
        Substitution("active dry yeast", [["self-rising flour"]], "only for quick breads: swap the flour instead"),
        Substitution("shortening", [["coconut oil"]], "solid coconut oil, same amount"),

        // Pantry & stocks
        Substitution("chicken broth", [["bouillon"], ["water"]], "1 cube or 1 tsp paste per cup of water", homemade: true),
        Substitution("chicken broth", [["vegetable broth"]], "vegetable broth, same amount"),
        Substitution("chicken broth", [["water"], ["butter"], ["salt"]], "water with a knob of butter and salt (lighter, still fine)", homemade: true),
        Substitution("beef broth", [["bouillon"], ["water"]], "1 cube or 1 tsp paste per cup of water", homemade: true),
        Substitution("beef broth", [["chicken broth"], ["soy sauce"]], "chicken broth with a splash of soy sauce", homemade: true),
        Substitution("beef broth", [["chicken broth"]], "chicken broth, same amount"),
        Substitution("vegetable broth", [["bouillon"], ["water"]], "1 cube or 1 tsp paste per cup of water", homemade: true),
        Substitution("vegetable broth", [["chicken broth"]], "chicken broth, same amount"),
        Substitution("tomato sauce", [["tomato paste"], ["water"]], "1 part paste to 1 part water", homemade: true),
        Substitution("tomato sauce", [["canned tomatoes"]], "canned tomatoes, blended smooth", homemade: true),
        Substitution("tomato paste", [["tomato sauce"]], "3 tbsp sauce per tbsp of paste, simmered down"),
        Substitution("tomato paste", [["ketchup"]], "ketchup, same amount (sweeter)"),
        Substitution("canned tomatoes", [["tomatoes"]], "fresh tomatoes, chopped, about 1½ lb per can"),
        Substitution("canned tomatoes", [["tomato sauce"]], "tomato sauce, same amount (smoother)"),
        Substitution("tomatoes", [["canned tomatoes"]], "canned diced tomatoes, drained"),
        Substitution("cream of mushroom soup", [["butter"], ["all-purpose flour"], ["milk"], ["mushrooms"]], "a white sauce with sautéed mushrooms: 2 tbsp butter, 2 tbsp flour, 1 cup milk", homemade: true),
        Substitution("cream of mushroom soup", [["butter"], ["all-purpose flour"], ["milk"]], "a plain white sauce: 2 tbsp butter, 2 tbsp flour, 1 cup milk", homemade: true),
        Substitution("cream of chicken soup", [["butter"], ["all-purpose flour"], ["chicken broth"], ["milk"]], "2 tbsp butter, 2 tbsp flour, ½ cup broth, ½ cup milk", homemade: true),
        Substitution("cream of chicken soup", [["cream of mushroom soup"]], "cream of mushroom, same amount"),
        Substitution("cream of mushroom soup", [["cream of chicken soup"]], "cream of chicken, same amount"),
        Substitution("rice", [["quinoa"]], "quinoa, cooked the same way"),
        Substitution("rice", [["couscous"]], "couscous, cooked per the package"),
        Substitution("brown rice", [["rice"]], "white rice, same amount, less cooking time"),
        Substitution("arborio rice", [["rice"]], "short or medium grain rice"),
        Substitution("pasta", [["egg noodles"]], "egg noodles, same amount"),
        Substitution("egg noodles", [["pasta"]], "any pasta, same amount"),
        Substitution("panko", [["bread crumbs"]], "plain bread crumbs, same amount"),
        Substitution("mayonnaise", [["yogurt"]], "plain yogurt, same amount"),
        Substitution("mayonnaise", [["sour cream"]], "sour cream, same amount"),
        Substitution("ketchup", [["tomato paste"], ["white vinegar"], ["granulated sugar"]], "tomato paste with a little vinegar and sugar", homemade: true),
        Substitution("dijon mustard", [["mustard"]], "yellow mustard, same amount"),
        Substitution("mustard", [["dijon mustard"]], "dijon, same amount"),
        Substitution("mustard", [["mustard powder"], ["water"]], "1 tsp dry mustard + 2 tsp water per tbsp", homemade: true),
        Substitution("worcestershire sauce", [["soy sauce"], ["ketchup"], ["white vinegar"]], "soy sauce with a dab of ketchup and a splash of vinegar", homemade: true),
        Substitution("worcestershire sauce", [["soy sauce"]], "soy sauce, same amount"),
        Substitution("soy sauce", [["worcestershire sauce"]], "worcestershire, same amount"),
        Substitution("fish sauce", [["soy sauce"]], "soy sauce, same amount"),
        Substitution("fish sauce", [["anchovies"]], "an anchovy or two, mashed"),
        Substitution("oyster sauce", [["hoisin sauce"], ["soy sauce"]], "hoisin thinned with soy sauce", homemade: true),
        Substitution("hoisin sauce", [["bbq sauce"], ["soy sauce"]], "bbq sauce with a splash of soy", homemade: true),
        Substitution("teriyaki sauce", [["soy sauce"], ["brown sugar"], ["garlic"]], "soy sauce simmered with brown sugar and garlic", homemade: true),
        Substitution("hot sauce", [["red pepper flakes"]], "a pinch of red pepper flakes"),
        Substitution("hot sauce", [["cayenne pepper"], ["white vinegar"]], "cayenne mixed into a little vinegar", homemade: true),
        Substitution("sriracha", [["hot sauce"]], "any hot sauce"),
        Substitution("bbq sauce", [["ketchup"], ["brown sugar"], ["apple cider vinegar"]], "ketchup, brown sugar and cider vinegar, simmered 5 minutes", homemade: true),
        Substitution("bbq sauce", [["ketchup"], ["brown sugar"], ["white vinegar"]], "ketchup, brown sugar and vinegar, simmered 5 minutes", homemade: true),
        Substitution("salsa", [["canned tomatoes"], ["onion"], ["lime"]], "diced tomatoes with chopped onion and a squeeze of lime", homemade: true),
        Substitution("pesto", [["basil"], ["olive oil"], ["parmesan"], ["garlic"]], "basil, garlic, parmesan and olive oil blitzed together", homemade: true),
        Substitution("ranch dressing", [["mayonnaise"], ["buttermilk"], ["dried dill"]], "mayo thinned with buttermilk, plus dill and garlic powder", homemade: true),
        Substitution("ranch dressing", [["mayonnaise"], ["milk"], ["ranch seasoning"]], "ranch seasoning mixed into mayo and milk", homemade: true),
        Substitution("italian dressing", [["olive oil"], ["red wine vinegar"], ["italian seasoning"]], "3 parts oil to 1 part vinegar, plus italian seasoning", homemade: true),
        Substitution("italian dressing", [["olive oil"], ["white vinegar"], ["italian seasoning"]], "3 parts oil to 1 part vinegar, plus italian seasoning", homemade: true),
        Substitution("taco seasoning", [["chili powder"], ["cumin"], ["garlic powder"], ["paprika"]], "1 tbsp chili powder, 1½ tsp cumin, ½ tsp each garlic powder and paprika, plus salt", homemade: true),
        Substitution("taco seasoning", [["chili powder"], ["cumin"]], "chili powder and cumin, 2 to 1, plus salt", homemade: true),
        Substitution("italian seasoning", [["dried oregano"], ["dried basil"]], "equal parts dried oregano and basil", homemade: true),
        Substitution("italian seasoning", [["dried oregano"]], "dried oregano, same amount"),
        Substitution("dried oregano", [["italian seasoning"]], "italian seasoning, same amount"),
        Substitution("cajun seasoning", [["paprika"], ["cayenne pepper"], ["garlic powder"], ["dried oregano"]], "paprika, cayenne, garlic powder and oregano", homemade: true),
        Substitution("old bay seasoning", [["celery salt"], ["paprika"], ["black pepper"]], "celery salt, paprika and pepper", homemade: true),
        Substitution("garlic", [["garlic powder"]], "⅛ tsp garlic powder per clove"),
        Substitution("garlic powder", [["garlic"]], "1 clove per ⅛ teaspoon, minced fine"),
        Substitution("onion", [["shallot"]], "shallots, about 3 per onion"),
        Substitution("onion", [["onion powder"]], "1 tsp onion powder per medium onion"),
        Substitution("onion", [["green onions"]], "a bunch of green onions"),
        Substitution("shallot", [["onion"]], "⅓ of a small onion per shallot"),
        Substitution("green onions", [["chives"]], "chives, same amount"),
        Substitution("green onions", [["onion"]], "a little finely diced onion"),
        Substitution("ginger", [["ginger powder"]], "¼ tsp ground ginger per tbsp fresh"),
        Substitution("lemon juice", [["lemon"]], "squeeze a lemon: about 3 tbsp each"),
        Substitution("lemon juice", [["lime juice"]], "lime juice, same amount"),
        Substitution("lemon juice", [["white vinegar"]], "half as much white vinegar"),
        Substitution("lime juice", [["lime"]], "squeeze a lime: about 2 tbsp each"),
        Substitution("lime juice", [["lemon juice"]], "lemon juice, same amount"),
        Substitution("lemon zest", [["lemon"]], "grate the peel of a lemon"),
        Substitution("lime zest", [["lime"]], "grate the peel of a lime"),
        Substitution("lemon", [["lemon juice"]], "bottled lemon juice, 3 tbsp per lemon"),
        Substitution("lime", [["lime juice"]], "bottled lime juice, 2 tbsp per lime"),
        Substitution("white vinegar", [["apple cider vinegar"]], "cider vinegar, same amount"),
        Substitution("white vinegar", [["lemon juice"]], "lemon juice, same amount"),
        Substitution("apple cider vinegar", [["white vinegar"]], "white vinegar, same amount"),
        Substitution("apple cider vinegar", [["red wine vinegar"]], "red wine vinegar, same amount"),
        Substitution("red wine vinegar", [["apple cider vinegar"]], "cider vinegar, same amount"),
        Substitution("red wine vinegar", [["balsamic vinegar"]], "balsamic, same amount (sweeter)"),
        Substitution("balsamic vinegar", [["red wine vinegar"], ["honey"]], "red wine vinegar with a little honey", homemade: true),
        Substitution("rice vinegar", [["apple cider vinegar"]], "cider vinegar, same amount"),
        Substitution("rice vinegar", [["white wine vinegar"]], "white wine vinegar, same amount"),
        Substitution("white wine vinegar", [["rice vinegar"]], "rice vinegar, same amount"),
        Substitution("white wine", [["chicken broth"]], "chicken broth, same amount"),
        Substitution("white wine", [["apple juice"], ["white vinegar"]], "apple juice with a splash of vinegar", homemade: true),
        Substitution("red wine", [["beef broth"]], "beef broth, same amount"),
        Substitution("red wine", [["cranberry juice"]], "cranberry juice, same amount"),
        Substitution("sherry", [["white wine"]], "dry white wine, same amount"),
        Substitution("bourbon", [["brandy"]], "brandy, same amount"),
        Substitution("brandy", [["bourbon"]], "bourbon, same amount"),
        Substitution("rum", [["bourbon"]], "bourbon, same amount"),
        Substitution("beer", [["chicken broth"]], "chicken broth, same amount"),
        Substitution("coconut milk", [["heavy cream"]], "cream, same amount"),
        Substitution("coconut milk", [["milk"], ["coconut flakes"]], "milk simmered with shredded coconut and strained", homemade: true),
        Substitution("olive oil", [["vegetable oil"]], "any neutral oil, same amount"),
        Substitution("vegetable oil", [["olive oil"]], "olive oil, same amount"),
        Substitution("vegetable oil", [["butter"]], "melted butter, same amount"),
        Substitution("vegetable oil", [["coconut oil"]], "melted coconut oil, same amount"),
        Substitution("coconut oil", [["butter"]], "butter, same amount"),
        Substitution("sesame oil", [["vegetable oil"], ["sesame seeds"]], "neutral oil with toasted sesame seeds", homemade: true),
        Substitution("cooking spray", [["vegetable oil"]], "a little oil on a paper towel"),
        Substitution("cooking spray", [["butter"]], "a little butter, rubbed on"),
        Substitution("capers", [["olives"]], "green olives, chopped"),
        Substitution("olives", [["capers"]], "capers, fewer"),
        Substitution("anchovies", [["fish sauce"]], "½ tsp fish sauce per fillet"),
        Substitution("bouillon", [["chicken broth"]], "use broth in place of the water"),
        Substitution("tahini", [["peanut butter"]], "peanut butter, same amount"),
        Substitution("peanut butter", [["almond butter"]], "almond butter, same amount"),
        Substitution("almond butter", [["peanut butter"]], "peanut butter, same amount"),
        Substitution("chickpeas", [["cannellini beans"]], "white beans, same amount"),
        Substitution("cannellini beans", [["chickpeas"]], "chickpeas, same amount"),
        Substitution("black beans", [["kidney beans"]], "kidney beans, same amount"),
        Substitution("black beans", [["pinto beans"]], "pinto beans, same amount"),
        Substitution("kidney beans", [["black beans"]], "black beans, same amount"),
        Substitution("pinto beans", [["black beans"]], "black beans, same amount"),
        Substitution("pinto beans", [["kidney beans"]], "kidney beans, same amount"),
        Substitution("lentils", [["split peas"]], "split peas, longer cook"),
        Substitution("quinoa", [["rice"]], "rice, same amount"),
        Substitution("couscous", [["quinoa"]], "quinoa, same amount"),
        Substitution("couscous", [["rice"]], "rice, same amount"),

        // Produce & herbs
        Substitution("cilantro", [["parsley"]], "flat-leaf parsley, same amount"),
        Substitution("parsley", [["cilantro"]], "cilantro, same amount"),
        Substitution("parsley", [["dried parsley"]], "1 tsp dried per tbsp fresh"),
        Substitution("basil", [["dried basil"]], "1 tsp dried per tbsp fresh"),
        Substitution("dill", [["dried dill"]], "1 tsp dried per tbsp fresh"),
        Substitution("thyme", [["dried oregano"]], "a little dried oregano"),
        Substitution("rosemary", [["thyme"]], "thyme, same amount"),
        Substitution("sage", [["thyme"]], "thyme, same amount"),
        Substitution("chives", [["green onions"]], "the green tops of scallions"),
        Substitution("shallot", [["red onion"]], "a little red onion"),
        Substitution("red onion", [["onion"]], "yellow onion, same amount"),
        Substitution("leek", [["onion"]], "onion, same amount"),
        Substitution("celery", [["fennel"]], "fennel, same amount"),
        Substitution("bell pepper", [["poblano pepper"]], "poblano, same amount"),
        Substitution("jalapeño", [["serrano pepper"]], "serrano, slightly fewer"),
        Substitution("jalapeño", [["red pepper flakes"]], "a pinch of red pepper flakes"),
        Substitution("chile peppers", [["jalapeño"]], "jalapeño, same amount"),
        Substitution("chile peppers", [["red pepper flakes"]], "a pinch of red pepper flakes"),
        Substitution("spinach", [["kale"]], "kale, stems removed, cooked a little longer"),
        Substitution("spinach", [["frozen spinach"]], "frozen spinach, thawed and squeezed dry"),
        Substitution("kale", [["spinach"]], "spinach, added at the very end"),
        Substitution("lettuce", [["spinach"]], "baby spinach"),
        Substitution("lettuce", [["cabbage"]], "shredded cabbage"),
        Substitution("zucchini", [["eggplant"]], "eggplant, same amount"),
        Substitution("butternut squash", [["sweet potatoes"]], "sweet potato, same amount"),
        Substitution("sweet potatoes", [["butternut squash"]], "butternut squash, same amount"),
        Substitution("sweet potatoes", [["potatoes"]], "potatoes, same amount"),
        Substitution("pumpkin", [["butternut squash"]], "butternut squash, roasted and mashed", homemade: true),
        Substitution("pumpkin", [["sweet potatoes"]], "sweet potato, cooked and mashed", homemade: true),
        Substitution("broccoli", [["cauliflower"]], "cauliflower, same amount"),
        Substitution("cauliflower", [["broccoli"]], "broccoli, same amount"),
        Substitution("green beans", [["asparagus"]], "asparagus, same amount"),
        Substitution("asparagus", [["green beans"]], "green beans, same amount"),
        Substitution("peas", [["edamame"]], "shelled edamame, same amount"),
        Substitution("mushrooms", [["eggplant"]], "eggplant, diced, for the texture"),
        Substitution("cherry tomatoes", [["tomatoes"]], "tomatoes, chopped"),
        Substitution("tomatoes", [["cherry tomatoes"]], "cherry tomatoes, halved"),
        Substitution("apples", [["pears"]], "pears, same amount"),
        Substitution("pears", [["apples"]], "apples, same amount"),
        Substitution("strawberries", [["raspberries"]], "raspberries, same amount"),
        Substitution("blueberries", [["blackberries"]], "blackberries, same amount"),
        Substitution("raspberries", [["strawberries"]], "strawberries, chopped"),
        Substitution("berries", [["frozen fruit"]], "frozen berries, not thawed"),
        Substitution("peaches", [["canned peaches"]], "canned peaches, drained"),
        Substitution("cranberries", [["dried cranberries"]], "dried cranberries, fewer"),
        Substitution("orange", [["lemon"]], "lemon, for the juice or zest"),
        Substitution("avocado", [["hummus"]], "hummus, as a spread"),
        Substitution("bananas", [["applesauce"]], "applesauce, same amount, in baking"),

        // Meat & protein
        Substitution("chicken breast", [["chicken thighs"]], "thighs, same weight, a few minutes longer"),
        Substitution("chicken thighs", [["chicken breast"]], "breasts, same weight, watch for dryness"),
        Substitution("chicken", [["turkey"]], "turkey, same amount"),
        Substitution("rotisserie chicken", [["chicken breast"]], "chicken breast, poached and shredded", homemade: true),
        Substitution("rotisserie chicken", [["chicken thighs"]], "chicken thighs, poached and shredded", homemade: true),
        Substitution("ground beef", [["ground turkey"]], "ground turkey, same amount"),
        Substitution("ground beef", [["ground pork"]], "ground pork, same amount"),
        Substitution("ground beef", [["ground chicken"]], "ground chicken, same amount"),
        Substitution("ground beef", [["italian sausage"]], "sausage, casings removed"),
        Substitution("ground turkey", [["ground chicken"]], "ground chicken, same amount"),
        Substitution("ground turkey", [["ground beef"]], "lean ground beef, same amount"),
        Substitution("ground pork", [["ground beef"]], "ground beef, same amount"),
        Substitution("ground pork", [["sausage"]], "bulk sausage, same amount"),
        Substitution("italian sausage", [["ground pork"], ["fennel seeds"], ["red pepper flakes"]], "ground pork seasoned with fennel and red pepper flakes", homemade: true),
        Substitution("italian sausage", [["sausage"]], "any pork sausage"),
        Substitution("sausage", [["ground pork"]], "ground pork, seasoned"),
        Substitution("bacon", [["pancetta"]], "pancetta, same amount"),
        Substitution("bacon", [["ham"]], "diced ham, same amount"),
        Substitution("pancetta", [["bacon"]], "bacon, same amount"),
        Substitution("prosciutto", [["ham"]], "thin-sliced ham"),
        Substitution("ham", [["bacon"]], "cooked bacon, crumbled"),
        Substitution("ham", [["deli turkey"]], "deli turkey, same amount"),
        Substitution("chorizo", [["italian sausage"], ["smoked paprika"]], "hot italian sausage with smoked paprika", homemade: true),
        Substitution("kielbasa", [["sausage"]], "any smoked or cooked sausage"),
        Substitution("pork chops", [["chicken breast"]], "chicken breast, same weight"),
        Substitution("lamb", [["beef"]], "beef, same cut"),
        Substitution("beef", [["pork"]], "pork, same cut"),
        Substitution("shrimp", [["scallops"]], "scallops, same amount"),
        Substitution("shrimp", [["white fish"]], "firm white fish, cubed"),
        Substitution("shrimp", [["chicken breast"]], "chicken, cubed"),
        Substitution("white fish", [["salmon"]], "salmon, same amount"),
        Substitution("salmon", [["white fish"]], "any firm fish, same amount"),
        Substitution("crab", [["shrimp"]], "shrimp, chopped"),
        Substitution("tofu", [["chicken breast"]], "chicken, cubed"),
        Substitution("tofu", [["chickpeas"]], "chickpeas, same amount"),

        // Bread and starch
        Substitution("bread", [["hamburger buns"]], "buns or rolls, split"),
        Substitution("hamburger buns", [["bread"]], "thick slices of bread, toasted"),
        Substitution("tortillas", [["pita bread"]], "pita, warmed"),
        Substitution("pita bread", [["tortillas"]], "flour tortillas"),
        Substitution("pie crust", [["all-purpose flour"], ["butter"], ["salt"]], "2½ cups flour, 1 cup cold butter, 1 tsp salt, ½ cup ice water", homemade: true),
        Substitution("pie crust", [["all-purpose flour"], ["shortening"], ["salt"]], "2½ cups flour, 1 cup shortening, 1 tsp salt, ½ cup ice water", homemade: true),
        Substitution("pizza dough", [["all-purpose flour"], ["active dry yeast"], ["olive oil"]], "3 cups flour, 1 packet yeast, 1 cup warm water, 2 tbsp oil, salt", homemade: true),
        Substitution("biscuit dough", [["all-purpose flour"], ["butter"], ["milk"], ["baking powder"]], "2 cups flour, 1 tbsp baking powder, 6 tbsp cold butter, ¾ cup milk", homemade: true),
        Substitution("pancake mix", [["all-purpose flour"], ["baking powder"], ["granulated sugar"]], "1 cup flour + 2 tsp baking powder + 1 tbsp sugar + ½ tsp salt", homemade: true),
        Substitution("cornbread mix", [["cornmeal"], ["all-purpose flour"], ["baking powder"]], "⅔ cup cornmeal, ½ cup flour, 1 tbsp baking powder, 3 tbsp sugar", homemade: true),
        Substitution("stuffing mix", [["bread"], ["celery"], ["onion"]], "cubed dried bread with sautéed celery and onion", homemade: true),
        Substitution("croutons", [["bread"]], "bread cubes toasted in oil", homemade: true),
        Substitution("crackers", [["bread crumbs"]], "bread crumbs, same amount"),
        Substitution("tortilla chips", [["tortillas"]], "tortillas cut into wedges and baked", homemade: true),
        Substitution("cake mix", [["all-purpose flour"], ["granulated sugar"], ["baking powder"]], "2 cups flour, 1½ cups sugar, 1 tbsp baking powder, ½ tsp salt, then the wet ingredients", homemade: true),
        Substitution("caramels", [["granulated sugar"], ["butter"], ["heavy cream"]], "sugar cooked to amber, then butter and cream stirred in", homemade: true),
        Substitution("whipped topping", [["heavy cream"]], "cream, whipped"),
        Substitution("ice cream", [["yogurt"]], "frozen yogurt or thick yogurt"),
        Substitution("coffee", [["espresso powder"], ["water"]], "instant espresso dissolved in hot water", homemade: true),
    ]

    /// Every rule for a target, in the order written, which is the order of
    /// preference.
    static let byTarget: [String: [Substitution]] = {
        var map: [String: [Substitution]] = [:]
        for rule in all { map[rule.target, default: []].append(rule) }
        return map
    }()

    /// The best substitution the pantry can actually make for `key`.
    static func available(for key: String, in index: PantryIndex) -> Substitution? {
        guard let rules = byTarget[key] else { return nil }
        return rules.first { rule in
            rule.options.allSatisfy { group in group.contains { index.has($0) } }
        }
    }

    /// Everything the catalogue knows about making do without `key`.
    static func ideas(for key: String) -> [Substitution] {
        byTarget[key] ?? []
    }
}
